import { build } from 'vite';
import { resolve } from 'path';
import { fileURLToPath } from 'url';
import { copyFileSync, cpSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'fs';
import { ensureDevDefaults } from './dev-defaults';

const __dirname = fileURLToPath(new URL('.', import.meta.url));
const sourcemap = process.argv.includes('--sourcemap');

// The phase31 pipeline (npm run build:full) generates the static ruleset plane and
// page-filtering artifacts into dist/ and injects them into dist/manifest.json.
// A plain `npm run build` wipes dist/ — without preservation that silently ships an
// extension with NO static blocking (regression: score collapses to baseline-only).
// Cache the generated plane across plain builds; build:full still regenerates it.
const PHASE31_CACHE = resolve(__dirname, '../node_modules/.cache/adapt-phase31-dist');
const PRESERVED_PATHS = ['phase31-rulesets', 'phase31', 'page-filtering', 'web-accessible-resources', 'phase31-page-cosmetic.css'];

interface PreservedPlane {
  manifest: Record<string, unknown>;
}

function preservePhase31Plane(distDir: string): PreservedPlane | undefined {
  const manifestPath = resolve(distDir, 'manifest.json');
  if (!existsSync(manifestPath)) return undefined;
  try {
    const manifest = JSON.parse(readFileSync(manifestPath, 'utf8')) as {
      declarative_net_request?: { rule_resources?: unknown[] };
    };
    const ruleResources = manifest.declarative_net_request?.rule_resources;
    if (!Array.isArray(ruleResources) || ruleResources.length === 0) return undefined;
    rmSync(PHASE31_CACHE, { recursive: true, force: true });
    mkdirSync(PHASE31_CACHE, { recursive: true });
    for (const entry of PRESERVED_PATHS) {
      const src = resolve(distDir, entry);
      if (existsSync(src)) cpSync(src, resolve(PHASE31_CACHE, entry), { recursive: true });
    }
    return { manifest: manifest as Record<string, unknown> };
  } catch {
    return undefined;
  }
}

function restorePhase31Plane(distDir: string, preserved: PreservedPlane | undefined): void {
  if (!preserved) {
    console.warn('PHASE31 STATIC PLANE: no cached rulesets — dist has NO static blocking; run npm run build:full before loading the extension');
    return;
  }
  try {
    for (const entry of PRESERVED_PATHS) {
      const cached = resolve(PHASE31_CACHE, entry);
      if (existsSync(cached)) cpSync(cached, resolve(distDir, entry), { recursive: true });
    }
    const manifestPath = resolve(distDir, 'manifest.json');
    const fresh = JSON.parse(readFileSync(manifestPath, 'utf8')) as Record<string, unknown> & {
      declarative_net_request?: { rule_resources?: unknown[] };
      web_accessible_resources?: unknown[];
    };
    const old = preserved.manifest as {
      declarative_net_request?: { rule_resources?: unknown[] };
      web_accessible_resources?: unknown[];
      content_scripts?: Array<Record<string, unknown>>;
    };
    if (old.declarative_net_request?.rule_resources) {
      fresh.declarative_net_request = {
        ...(fresh.declarative_net_request ?? {}),
        rule_resources: old.declarative_net_request.rule_resources,
      };
    }
    if (Array.isArray(old.web_accessible_resources) && !Array.isArray(fresh.web_accessible_resources)) {
      fresh.web_accessible_resources = old.web_accessible_resources;
    }
    // The page plane's manifest declarations are only regenerated by
    // build:full (phase31:page). Carry them over on incremental builds or the
    // dist silently loses the pre-paint cosmetic css and every per-domain
    // early MAIN-world scriptlet.
    if (Array.isArray(old.content_scripts)) {
      const freshScripts = ((fresh as { content_scripts?: Array<Record<string, unknown>> }).content_scripts ??= []);
      const hasJs = (entry: Record<string, unknown>, name: string) => Array.isArray(entry.js) && (entry.js as unknown[]).includes(name);
      const isEarlyEntry = (entry: Record<string, unknown>) => Array.isArray(entry.include_globs);
      const oldContent = old.content_scripts.find((entry) => hasJs(entry, 'content.js'));
      const freshContent = freshScripts.find((entry) => hasJs(entry, 'content.js'));
      const oldCss = Array.isArray(oldContent?.css) ? (oldContent.css as unknown[]).filter((value): value is string => typeof value === 'string') : [];
      if (freshContent && oldCss.length > 0) {
        const css = Array.isArray(freshContent.css) ? (freshContent.css as unknown[]).filter((value): value is string => typeof value === 'string') : [];
        for (const item of oldCss) if (!css.includes(item)) css.push(item);
        freshContent.css = css;
      }
      // css may be declared on any entry (the page-filtering build attaches it
      // to the first matching entry). Restore css per originating js bundle.
      for (const oldEntry of old.content_scripts) {
        const entryCss = Array.isArray(oldEntry.css) ? (oldEntry.css as unknown[]).filter((value): value is string => typeof value === 'string') : [];
        if (entryCss.length === 0 || !Array.isArray(oldEntry.js)) continue;
        const freshEntry = freshScripts.find((entry) => JSON.stringify(entry.js) === JSON.stringify(oldEntry.js));
        if (!freshEntry || freshEntry === freshContent) continue;
        const css = Array.isArray(freshEntry.css) ? (freshEntry.css as unknown[]).filter((value): value is string => typeof value === 'string') : [];
        for (const item of entryCss) if (!css.includes(item)) css.push(item);
        freshEntry.css = css;
      }
      for (const early of old.content_scripts.filter(isEarlyEntry)) {
        const key = JSON.stringify([early.include_globs, early.js]);
        if (!freshScripts.filter(isEarlyEntry).some((entry) => JSON.stringify([entry.include_globs, entry.js]) === key)) {
          freshScripts.push(early);
        }
      }
    }
    writeFileSync(manifestPath, JSON.stringify(fresh, null, 2));
    console.log('PHASE31 STATIC PLANE: preserved from cache (run npm run build:full to regenerate)');
  } catch {
    console.warn('PHASE31 STATIC PLANE: cache restore failed — run npm run build:full');
  }
}

async function buildExtension() {
  // 0. Bake the dev-only AI default config (gitignored credential, or undefined stub)
  const devAiBaked = ensureDevDefaults();
  console.log(`DEV AI DEFAULT: ${devAiBaked ? 'configured (gitignored)' : 'absent — stub written'}`);

  const distDir = resolve(__dirname, '../dist');
  const preservedPlane = preservePhase31Plane(distDir);
  rmSync(distDir, { recursive: true, force: true });
  mkdirSync(distDir, { recursive: true });
  mkdirSync(resolve(distDir, 'rules'), { recursive: true });
  mkdirSync(resolve(distDir, 'popup'), { recursive: true });

  // 1. Build Background Service Worker (Self-contained, no external chunk imports)
  await build({
    configFile: false,
    build: {
      outDir: distDir,
      emptyOutDir: false,
      lib: {
        entry: resolve(__dirname, '../src/entrypoints/background.ts'),
        name: 'background',
        formats: ['es'],
        fileName: () => 'background.js',
      },
      rollupOptions: {
        output: {
          inlineDynamicImports: true,
        },
      },
    },
  });

  // 2. Build Content Script (Self-contained IIFE, no external chunk imports)
  await build({
    configFile: false,
    build: {
      outDir: distDir,
      emptyOutDir: false,
      sourcemap,
      minify: sourcemap ? false : 'esbuild',
      lib: {
        entry: resolve(__dirname, '../src/entrypoints/content.ts'),
        name: 'content',
        formats: ['iife'],
        fileName: () => 'content.js',
      },
      rollupOptions: {
        output: {
          inlineDynamicImports: true,
        },
      },
    },
  });

  // 2b. Build the stealth-plane MAIN-world bootstrap (deterministic anti-detector
  // flag seeding; fully self-contained IIFE).
  await build({
    configFile: false,
    build: {
      outDir: distDir,
      emptyOutDir: false,
      minify: sourcemap ? false : 'esbuild',
      lib: {
        entry: resolve(__dirname, '../src/entrypoints/stealth-main.ts'),
        name: 'stealthMain',
        formats: ['iife'],
        fileName: () => 'stealth-main.js',
      },
      rollupOptions: {
        output: {
          inlineDynamicImports: true,
        },
      },
    },
  });

  // 2. Build the document-start MAIN-world popup broker.
  await build({
    configFile: false,
    build: {
      outDir: distDir,
      emptyOutDir: false,
      minify: sourcemap ? false : 'esbuild',
      lib: {
        entry: resolve(__dirname, '../src/entrypoints/early-popup-broker.ts'),
        name: 'popupBroker',
        formats: ['iife'],
        fileName: () => 'popup-broker.js',
      },
      rollupOptions: {
        output: {
          inlineDynamicImports: true,
        },
      },
    },
  });

  // 4. Build Popup HTML / CSS / TS
  await build({
    configFile: false,
    root: resolve(__dirname, '../src/entrypoints/popup'),
    base: '',
    build: {
      outDir: resolve(distDir, 'popup'),
      emptyOutDir: false,
      rollupOptions: {
        input: resolve(__dirname, '../src/entrypoints/popup/index.html'),
      },
    },
  });

  // 4b. Build Options page (AI planner development configuration surface)
  await build({
    configFile: false,
    root: resolve(__dirname, '../src/entrypoints/options'),
    base: '',
    build: {
      outDir: resolve(distDir, 'options'),
      emptyOutDir: false,
      rollupOptions: {
        input: resolve(__dirname, '../src/entrypoints/options/index.html'),
      },
    },
  });

  // 5. Copy manifest.json & static rules
  copyFileSync(
    resolve(__dirname, '../src/manifest.json'),
    resolve(distDir, 'manifest.json')
  );

  copyFileSync(
    resolve(__dirname, '../src/rules/static/baseline.json'),
    resolve(distDir, 'rules/baseline.json')
  );

  // 5b. Toolbar/store icons (generated from the brand tile; the 1254px source
  // stays in src/icons and is never shipped).
  const iconsDist = resolve(distDir, 'icons');
  mkdirSync(iconsDist, { recursive: true });
  for (const size of [16, 32, 48, 128]) {
    copyFileSync(resolve(__dirname, `../src/icons/icon-${size}.png`), resolve(iconsDist, `icon-${size}.png`));
  }

  // 6. Restore the generated phase31 static/page plane wiped by the dist clean.
  restorePhase31Plane(distDir, preservedPlane);

  // 7. Install the stealth plane (anti-detector shims + redirect ruleset).
  //    Idempotent; v6.mjs re-asserts it after build:full regenerates the manifest.
  try {
    // Plain-mjs module without type declarations; the contract is the single
    // idempotent installStealthPlane function.
    // @ts-expect-error untyped .mjs tool module
    const { installStealthPlane } = (await import('../tools/stealth/install-shims.mjs')) as unknown as {
      installStealthPlane: (dir?: string) => { installed: boolean; shims?: number; rules?: number; reason?: string };
    };
    const stealth = installStealthPlane(distDir);
    console.log(`STEALTH PLANE: ${stealth.installed ? `installed (${stealth.shims} shims, ${stealth.rules} redirect rules)` : `SKIPPED (${stealth.reason})`}`);
  } catch (error) {
    console.warn('STEALTH PLANE: install failed —', error);
  }

  console.log('ADAPT extension successfully built to dist/');
}

buildExtension().catch((err) => {
  console.error(err);
  process.exit(1);
});
