/**
 * Generates src/background/ai/dev-defaults.ts — the DEVELOPMENT-ONLY built-in AI
 * planner config baked into private local builds so the installed extension works
 * without manual Options-page configuration.
 *
 * The credential is sourced at build time from AZURE_OPENAI_API_KEY or the Azure
 * CLI and is written only into this gitignored generated file. It is never
 * committed, logged, or copied into artifacts. When no credential is available a
 * stub exporting `undefined` is written so builds never break.
 *
 * Configuration (all optional; with none set, the undefined stub is written):
 *   AZURE_OPENAI_BASE_URL       full endpoint, e.g. https://<account>.openai.azure.com/openai/v1
 *   AZURE_OPENAI_API_KEY        API key (or resolved via az CLI when ACCOUNT+RG are set)
 *   AZURE_OPENAI_ACCOUNT        Azure OpenAI account name (for az CLI key lookup)
 *   AZURE_OPENAI_RESOURCE_GROUP resource group (for az CLI key lookup)
 *   AZURE_OPENAI_MODEL          deployment/model name
 */

import { execSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const outPath = resolve(__dirname, '../src/background/ai/dev-defaults.ts');

const ENDPOINT = process.env.AZURE_OPENAI_BASE_URL?.replace(/\/?$/, '/chat/completions');
const MODEL = process.env.AZURE_OPENAI_MODEL;

function resolveToken(): string | undefined {
  if (process.env.AZURE_OPENAI_API_KEY) return process.env.AZURE_OPENAI_API_KEY.trim();
  const account = process.env.AZURE_OPENAI_ACCOUNT;
  const resourceGroup = process.env.AZURE_OPENAI_RESOURCE_GROUP;
  if (!account || !resourceGroup) return undefined;
  try {
    const key = execSync(
      `az cognitiveservices account keys list --name ${account} --resource-group ${resourceGroup} --query key1 -o tsv`,
      { encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'], timeout: 15000 }
    ).trim();
    return key.length > 0 ? key : undefined;
  } catch {
    return undefined;
  }
}

export function ensureDevDefaults(): boolean {
  // Test/CI builds must stay deterministic: ADAPT_SKIP_BAKED_AI=1 writes the
  // undefined stub so no test can accidentally fire real provider calls.
  // A baked config needs endpoint + model + token; any gap falls back to the stub.
  const resolved = process.env.ADAPT_SKIP_BAKED_AI === '1' ? undefined : resolveToken();
  const token = resolved && ENDPOINT && MODEL ? resolved : undefined;
  const body =
    token === undefined
      ? `// GENERATED by scripts/dev-defaults.ts — no credential available at build time.\n` +
        `import { AiConfig } from './remote-planner';\n\n` +
        `export const DEV_DEFAULT_AI_CONFIG: AiConfig | undefined = undefined;\n`
      : `// GENERATED by scripts/dev-defaults.ts — DEVELOPMENT-ONLY, gitignored, never commit.\n` +
        `// The token below is a live credential for a private local build only.\n` +
        `import { AiConfig } from './remote-planner';\n\n` +
        `export const DEV_DEFAULT_AI_CONFIG: AiConfig | undefined = {\n` +
        `  endpoint: ${JSON.stringify(ENDPOINT)},\n` +
        `  token: ${JSON.stringify(token)},\n` +
        `  model: ${JSON.stringify(MODEL)},\n` +
        `  privacyMode: 'STRICT',\n` +
        `  timeoutMs: 30000,\n` +
        `};\n`;
  writeFileSync(outPath, body, 'utf8');
  return token !== undefined;
}

if (process.argv[1] && resolve(process.argv[1]) === resolve(fileURLToPath(import.meta.url))) {
  const written = ensureDevDefaults();
  console.log(`dev-defaults: ${written ? 'credential baked into gitignored dev-defaults.ts' : 'no credential — wrote undefined stub'}`);
}
